### ISSUE TITLE
`bundle install --without` fails

### ISSUE THREAD

**Issue by tmm1** [twitter-forks/rubyenterpriseedition187-248#2]
```
$ ruby -v
ruby 1.8.7 (2010-04-19 patchlevel 253) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2010.02, Kiji 0.11

$ bundle -v
Bundler version 1.0.15

$ bundle install --without test
/var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/cli.rb:157:in `map!': can't modify frozen array (TypeError)
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/cli.rb:157:in `install'
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/vendor/thor/task.rb:22:in `send'
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/vendor/thor/task.rb:22:in `run'
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/vendor/thor.rb:246:in `dispatch'
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/lib/bundler/vendor/thor/base.rb:389:in `start'
    from /var/lib/jenkins/.rvm/gems/kiji-head/gems/bundler-1.0.15/bin/bundle:13
    from /var/lib/jenkins/.rvm/gems/kiji-head/bin/bundle:19:in `load'
    from /var/lib/jenkins/.rvm/gems/kiji-head/bin/bundle:19
```

**Comment by tmm1** [comment]
Submitted fix to bundler: https://github.com/carlhuda/bundler/pull/1287
