### ISSUE TITLE
Symbol not found: _system_free

### ISSUE THREAD

**Issue by bleonard** [twitter-forks/rubyenterpriseedition187-248#4]
I can just not get this to work.
Running OS X Lion.

I'm getting this...
dyld: lazy symbol binding failed: Symbol not found: _system_free
  Referenced from: /Users/bleonard/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin11.1.0/readline.bundle
  Expected in: flat namespace

My current attempt

rvm pkg install iconv
rvm pkg install readline
export CC=/usr/bin/gcc-4.2
export ARCHFLAGS="-arch x86_64"
rvm install kiji --with-iconv-dir=$rvm_path/usr --with-readline-dir=$rvm_path/.rvm/usr

cd ~/rails_app
rvm use kiji
gem install bundler
bundle install

script/console

> > User.new.email
> > dyld: lazy symbol binding failed: Symbol not found: _system_free
> >   Referenced from: /Users/bleonard/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin11.1.0/readline.bundle
> >   Expected in: flat namespace

dyld: Symbol not found: _system_free
  Referenced from: /Users/bleonard/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin11.1.0/readline.bundle
  Expected in: flat namespace

Trace/BPT trap: 5

**Comment by diclophis** [comment]
I am also running into this same problem.

System details:
- OSX 10.6.6
- rvm 1.8.6 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]
- Rails 2.3.14
- Bundler version 1.0.21
- gem 1.8.10
- ruby 1.8.7 (2010-04-19 patchlevel 253) [i686-darwin10.6.0], MBARI 0x6770, Ruby Enterprise Edition 2010.02, Kiji 0.11

When I attempt to run my test suite, I get errors related to Mysql::Res which are typically solved by setting the ARCHFLAGS option when building the mysql gem, but then I also attempted to load the ./script/console and received this message:

```
Bundle exec ./script/console 
Loading development environment (Rails 2.3.14)
Readline was unable to be required, if you need completion or history install readline then reinstall the ruby.
You may follow 'rvm notes' for dependencies and/or read the docs page https://rvm.beginrescueend.com/packages    /readline/ . Be sure you 'rvm remove X ; rvm install X' to re-compile your ruby with readline support after obtaining the readline libraries.
/Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin10.6.0/readline.bundle: dlopen(/Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin10.6.0/readline.bundle, 9): Symbol not found: _system_free (LoadError)
  Referenced from: /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin10.6.0/readline.bundle
  Expected in: flat namespace
 in /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/i686-darwin10.6.0/readline.bundle - /Users/jon/.rvm/rubies/kiji-head/lib /ruby/1.8/i686-darwin10.6.0/readline.bundle
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb/completion.rb:10
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb/init.rb:254:in `require'
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb/init.rb:254:in `load_modules'
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb/init.rb:252:in `each'
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb/init.rb:252:in `load_modules'
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb/init.rb:21:in `setup'
    from /Users/jon/.rvm/rubies/kiji-head/lib/ruby/1.8/irb.rb:54:in `start'
    from /Users/jon/.rvm/rubies/kiji-head/bin/irb:17
```

**Comment by NewAlexandria** [comment]
did either of you ever solve this issue?  Does this require reinstalling readline?  The problem happens for me whenever I try to access a variable in the ruby debugger.

**Comment by diclophis** [comment]
I have not made any progress towards this... pretty much moved my efforts onto the newer builds of REE from phusion

**Comment by NewAlexandria** [comment]
I think the problem is readline linkage in my rbenv local config of REE.

Since this problem happened for me with rdebug & pry, I switched off of REE locally to run tests.
